Curated results
sitecrafting/sitka-insights-wordpress pull request #13
Opened 2024-10-24 17:18 UTC by akoziolsc

Added curated results functionality to the plugin. 

- Switched `gearlab-tools-php` dependency to use `curated-search` branch (to get the curated result capability available on the SDK level).
- Added templates to handle `quick_links` template 
- Added set of field templates to cover available curated result field types out of the box
- Added enable/disable toggle to the plugin settings
- Implemented basic style for curated results section

Contact @akoziolsc for details on testing setup of the plugin.

2024-10-28 23:56 UTC, sdunham commented on views/frontend/curated-result-field-templates/curated-result-field-template-button.php
I'm going to add this once on this file as a general comment that applies to all the curated result field templates. It's also 100% a take it or leave it kind of comment. I don't feel strongly that you **_need_** to take action on this, but it's the kind of thing that I would personally do.

Because all the curated result field values are variable in terns of what they contain, and there aren't any types to rely on, it might be worth adding some checks to ensure each field type has a baseline of the data you expect to be able to successfully render out a given template, and short circuit the render of that field if not. e.g. does a button field have at least a URL and link text, does a headline field have headline text, etc...

2024-10-29 00:06 UTC, sdunham requested changes
I'll hit you up tomorrow about getting this set up locally so I can test, but in the meantime I added a few small comments/questions to this PR.

2024-10-29 00:06 UTC, sdunham commented on views/frontend/search-results.php
> +$curatedResultsEnables = $response['curatedResultsEnabled'] ?? false;
Not important, but a tiny typo on this variable name

2024-10-29 00:06 UTC, sdunham commented on views/settings-meta.php
> +      /* Option removed per request from Phil Price
If we're removing this option, I'm assuming we'll need to address any other place this option is used in this plugin to avoid issues where this might have been set to staging but now we're assuming it should always be set to production.

2024-10-29 00:06 UTC, sdunham commented on css/sitka-insights-search.css
Just out of curiosity, did anyone on the FE team consult on the styles/markup for curated results? Also, looks like there might be some slight formatting issues with some of the CSS that was added to this file.

2024-10-29 14:13 UTC, akoziolsc commented on css/sitka-insights-search.css
I was working with Leah on dressing it up a little bit.  I'm curious about you concerns.

2024-10-29 14:22 UTC, akoziolsc commented on views/settings-meta.php
> +      /* Option removed per request from Phil Price
Removing this options will not affect anything.  The filters responsible for changing the API URIs will honor `staging` option and will switch URI accordingly. This is more so the admins can not change it. The option still exists for the developers if needed. This is why I gig not remove this option from the form completely. I will add a comment to this.

2024-10-29 16:27 UTC, sdunham commented on css/sitka-insights-search.css
No concerns (especially since I haven't spun this up to see what it looks like yet). Just curious. Figured if we're adding default markup/styles to the plugin, it would make sense to involve the FE team at some point. Sounds like that's already happening.

2024-10-29 16:30 UTC, sdunham commented on views/settings-meta.php
> +      /* Option removed per request from Phil Price
k. I was more concerned about the scenario where the plugin is already set up to connect to stg, then the plugin gets updated and there's no way to know that it had previously been set to stg or update it via the UI. But I suppose the comment you're adding should help in that (kinda unlikely, but possible) scenario.

2024-10-29 16:46 UTC, akoziolsc commented on views/frontend/curated-result-field-templates/curated-result-field-template-button.php
Added some checks to each field template.

2024-10-29 16:47 UTC, akoziolsc commented on views/frontend/search-results.php
> +$curatedResultsEnables = $response['curatedResultsEnabled'] ?? false;
Fixed the typo. Thanks.

2024-10-29 17:15 UTC, sdunham approved these changes
This looks good to me.

One quick note: @akoziolsc is going to bump the plugin version to 3.0 and add a changelog to make it clear to any users of the legacy curated results functionality that there's a potential breaking change for them in this version of the plugin.

2024-10-29 22:37 UTC, merged